[build]
  command   = "npm install"
  publish   = "public"
  functions = "netlify/functions"

[dev]
  command = "node server.js"
  port    = 3000

[functions]
  # เปลี่ยนจาก esbuild เป็น zisi เพื่อแก้ปัญหาโมดูลหาย
  node_bundler = "zisi" 
  # ดักเผื่อไว้ทั้ง 2 กรณีว่าโฟลเดอร์ views อยู่ข้างนอก หรืออยู่ในโฟลเดอร์ src
  included_files = ["views/**", "src/views/**"]

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/server"
  status = 200